name: AIGS

on: [push, pull_request]

jobs:
  Build:
    name: Build AIGS
    runs-on: windows-latest

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1  

    - name: Checkout AIGS repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Intall AIGS dependencies
      run: msbuild -t:restore -p:RestorePackagesConfig=true

    - name: Build AIGS artifact
      run: msbuild AIGS.csproj -verbosity:diag -property:Configuration=Debug

    - name: Upload AIGS artifact
      uses: actions/upload-artifact@v3
      with:
        name: AIGS
        path: bin\Debug\AIGS.dll
